require('proof')(10, prove)

function prove (assert) {
    var Supersede = require('../../supersede')
    var set = new Supersede('z')

    assert(set.get('.hello'.split('.')), 'z', 'empty get')
    set.set([ '' ], 'a')
    assert(set.get('.hello'.split('.')), 'a', 'root get')
    set.set('.hello.world'.split('.'), 'x')
    set.set('.hello.nurse'.split('.'), 'y')
    assert(set.get('.hello'.split('.')), 'a', 'short path get')
    assert(set.get('.hello.nurse'.split('.')), 'y', 'full path get')
    set.set('.hello'.split('.'), 'c')
    assert(set.get('.hello'.split('.')), 'c', 'parent get')
    set.remove('.hello.nurse'.split('.'))
    assert(set.get('.hello.world'.split('.')), 'x', 'child get')
    assert(set.get('.hello.nurse'.split('.')), 'c', 'child get parent value')
    set.set('.hello.nurse'.split('.'), 'y')
    assert(set.get('.hello.nurse'.split('.')), 'y', 'child reset get')
    set.remove('.hello.*'.split('.'))
    assert(set.get('.hello.world'.split('.')), 'c', 'delete all one')
    assert(set.get('.hello.nurse'.split('.')), 'c', 'delete all two')
    set.remove('.hello.nurse.*'.split('.'))
}
